healthy_fats = ['olive oil', 'sunflower oil', 'soybean oil', 'corn oil',  'sesame oil',  'peanut oil', 'vegtable oil', 'coconut oil', 'avocado' , 'olives'  ]
healthy_protein = [ 'peas',  'beans', 'eggs', 'crab', 'fish','chicken', 'tofu', 'liver', 'turkey', 'egg whites', 'penut butter', 'almonds', 'salmon', 'hummus' ]
healthy_dairy = [ 'fat free milk', 'low fat milk', 'yogurt',  'low fat cheese', 'greek yogurt', 'almond milk', 'soy milk', 'goat cheese']
healthy_salts = ['low sodium soy sauce', 'sea salt', 'kosher salt']
healthy_grains = ['oat cereal', 'wild rice', 'oatmeal', 'whole rye', 'buckwheat', 'rolled oats', 'quinoa','bulgur', 'millet', 'brown rice', 'whole wheat pasta']
healthy_sugars = ['real fruit jam', 'fruit juice concentrates', 'monk fruit extract', 'cane sugar', 'molasses', 'brown rice syrup' 'stevia', 'honey', 'maple syrup', 'agave syrup', 'coconut sugar', 'date sugar', 'sugar alcohols', 'brown sugar']
