ubstitutions = {
    'macaroni': 'whole wheat macaroni', 
	'noodles': 'buckwheat spaghetti', 
	'spaghetti': 'whole wheat spaghetti', 
	'white rice': 'brown rice', 
	'rice': 'brown rice',
	'bread': 'whole wheat bread', 
	'pasta': 'whole wheat pasta'
    'reduced-fat milk': 'fat free milk', 
	'cream cheese': 'low fat cream cheese', 
	'whole milk' : 'fat free milk', 
	'milk': 'fat free milk',
	'butter': 'olive oil', 
	'cheese': 'low fat cheese', 
	'whipped cream': 'fat free yogurt',  
	'sour cream': 'fat free yogurt'
    'butter': 'olive oil', 
	'lard': 'olive oil', 
	'shortening': 'olive oil', 
	'canola oil': 'olive oil', 
	'margarine': 'olive oil',  
	'coconut oil': 'avocado oil',  
	'tallow': 'soybean oil',   
	'palm oil': 'sunflower oil',  
	'palm kemel oil': 'sunflower oil',  
	'chicken fat': 'olive oil',  
	'hydrogenated oils': 'non-hydrogenated oils'
    'unhealthy':'healthy',
    'ground beef':'lean ground turkey',
    'bacon':'canadian bacon',
    'sausage':'lean ham',
    'chicken':'skinless chicken',
    'thigh': 'breast',
    'turkey':'skinless turkey',
    'duck':'skinless turkey',
    'goose':'skinless turkey',
    'beef' :'beef loin',
    'beef chuck':'beef loin',
    'beef rib':'beef loin',
    'beef brisket':'beef loin',
    'pork spareribs':'pork tenderloin',
    'chorizo sausage':'turkey sausage',
    'milk':'skim milk',
    'cream':'evaporated skim milk',
    'iceberg lettuce':'arugula',
    'butter':'cooking spray',
    'margarine':'olive oil',
    'cheddar cheese': "low-fat cheddar cheese",
    'mozzerella cheese': "low-fat mozzerella cheese",
    'american cheese': "low-fat american cheese",
    'cottage cheese': 'low-fat cottage cheese',
    'vegetable oil':'olive oil',
    'shortening':'fat-free margarine',
    'soy sauce':'low-sodium soy sauce',
    'alfredo':'marinara',
    'pasta':'whole wheat pasta',
    'sour cream':'Greek yogurt',
    'bread':'pita',
    'flour tortilla':'corn tortilla',
    'white bread':'whole wheat bread',
    'bread' : 'whole wheat bread',
    'mayonnaise':'Greek yogurt',
    'eggs':'egg whites',
    'cream cheese':'fat-free ricotta cheese',
    'white rice':'brown rice', 
    'salted' : 'unsalted'
}